### ISSUE TITLE
Missing roentgen.raster in repo

### ISSUE THREAD

**Issue by bugim** [enzet/Roentgen#61]
I like your project. Tried to play with but i might have a newbie issue. I miss roentgen.raster in the repo.

**Comment by enzet** [comment]
Yeah, sorry, my bad. It's just a lack of integration tests. Forgot to add a file.

Thank you for the feedback!

**Comment by enzet** [comment]
Looks like now it works on the freshly cloned repo.

Thank you for your interest and participation!

**Comment by enzet** [comment]
Well, I've added the simplest integration test in #62, now at least it shouldn't fail on the examples from the readme. 😅
